# Generated by Django 3.2.24 on 2024-02-25 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_new_options_new_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('new', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.new')),
            ],
        ),
    ]
