# Generated by Django 3.2.24 on 2024-02-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_newsdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsDetail',
        ),
    ]
